import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/themeprovider";
import SiteHeader from "../components/siteheader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Personlig nettside",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>👩🏼‍💻</text></svg>"
        />
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SiteHeader></SiteHeader>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
