import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SiteHeader from "../components/site-header";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Personal website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="no-nb">
      <body className={clsx("light", inter.className)}>{children}</body>
    </html>
  );
}
