import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SiteHeader from "../components/site-header";

export const metadata: Metadata = {
  title: "Personal website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="no-nb">
      <body className="bg-[#bae1ff]">
        <SiteHeader />
        {children}
        <footer className="bg-green-500 h-20"></footer>
      </body>
    </html>
  );
}
